# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Kc India Mart' do

pod 'AFNetworking', '~> 2.0’
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'
pod 'Google/SignIn'
pod 'MMDrawerController', '~> 0.5.7'
pod 'JSONModel'
pod 'ZBarSDK'
pod 'SDWebImage', '~>3.6’


end


